version: 2.1
jobs:
  backend_test:
    docker:
      - image: circleci/node:14
    working_directory: ~/backend
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
          unzip sonar-scanner.zip
          ./sonar-scanner-4.7.0.2747-linux/bin/sonar-scanner \
            -Dsonar.projectKey=uzaircotwall_apds7311-poe \
            -Dsonar.organization=uzaircotwall \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN

  frontend_test:
    docker:
      - image: circleci/node:14
    working_directory: ~/frontend
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
          unzip sonar-scanner.zip
          ./sonar-scanner-4.7.0.2747-linux/bin/sonar-scanner \
            -Dsonar.projectKey=uzaircotwall_apds7311-poe \
            -Dsonar.organization=uzaircotwall \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  test:
    jobs:
      - backend_test
      - frontend_test
